name: '✨ CoriAI Code Review, PhD'
description: '🤖 AI-powered code reviews for pull requests using LLMs, by a smart human with a PhD! 🎓'
author: 'theboringhumane'

branding:
  icon: 'anchor'
  color: 'purple'

inputs:
  provider:
    description: 'LLM provider to use (openai, gemini, groq, mistral, ollama-local, ollama-cloud)'
    required: false
    default: 'openai'
  
  # OpenAI settings
  openai_api_key:
    description: 'OpenAI API key (required if using OpenAI)'
    required: false
  openai_base_url:
    description: 'OpenAI API base URL (optional)'
    required: false
    default: 'https://api.openai.com/v1'
  
  # Google Gemini settings
  google_api_key:
    description: 'Google API key (required if using Gemini)'
    required: false
  
  # Groq settings
  groq_api_key:
    description: 'Groq API key (required if using Groq)'
    required: false
  
  # Mistral settings
  mistral_api_key:
    description: 'Mistral API key (required if using Mistral)'
    required: false
  
  # Ollama settings
  ollama_api_key:
    description: 'Ollama API key (required if using Ollama)'
    required: false
  ollama_base_url:
    description: 'Ollama API base URL (optional)'
    required: false
    default: 'http://localhost:11434'
  
  # Common settings
  github_token:
    description: 'GitHub token for PR access'
    required: false
    default: ${{ github.token }}
  extra_prompt:
    description: 'Additional instructions for the AI reviewer'
    required: false
    default: ''
  model:
    description: 'Model to use (provider-specific, e.g., gpt-4-turbo-preview for OpenAI, gemini-pro for Google)'
    required: false
    default: 'gpt-4o-mini'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_PROVIDER: ${{ inputs.provider }}
    INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    INPUT_OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
    INPUT_GOOGLE_API_KEY: ${{ inputs.google_api_key }}
    INPUT_GROQ_API_KEY: ${{ inputs.groq_api_key }}
    INPUT_OLLAMA_API_KEY: ${{ inputs.ollama_api_key }}
    INPUT_OLLAMA_BASE_URL: ${{ inputs.ollama_base_url }}
    INPUT_MISTRAL_API_KEY: ${{ inputs.mistral_api_key }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_MODEL: ${{ inputs.model }}
    INPUT_EXTRA_PROMPT: ${{ inputs.extra_prompt }}
    PR_TITLE: ${{ github.event.pull_request.title }}
    PR_DESCRIPTION: ${{ github.event.pull_request.body }}
    PR_STATE: ${{ github.event.pull_request.state }}
    PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    PR_NUMBER: ${{ github.event.number }}
    GITHUB_REPOSITORY: ${{ github.repository }}