name: '✨ CoriAI Code Review, PhD'
description: '🤖 AI-powered code reviews for pull requests using LLMs, by a smart human with a PhD! 🎓'
author: 'theboringhumane'

branding:
  icon: 'anchor'
  color: 'purple'

inputs:
  pr_number:
    description: 'Pull request number'
    required: true
  
  provider:
    description: 'LLM provider to use (openai, gemini, groq, or mistral, or anthropic, or ollama)'
    required: false
    default: 'openai'
  
  openai_api_key:
    description: 'OpenAI API key'
    required: false
  
  openai_base_url:
    description: 'OpenAI API base URL'
    required: false
    default: 'https://api.openai.com/v1'
  
  google_api_key:
    description: 'Google API key'
    required: false
  
  groq_api_key:
    description: 'Groq API key'
    required: false
  
  mistral_api_key:
    description: 'Mistral API key'
    required: false
  
  # Ollama settings
  ollama_api_key:
    description: 'Ollama API key (required if using Ollama)'
    required: false
  ollama_base_url:
    description: 'Ollama API base URL (optional)'
    required: false
    default: 'http://localhost:11434'
  
  # Common settings
  github_token:
    description: 'GitHub token for PR access'
    required: false
    default: ${{ github.token }}
  extra_prompt:
    description: 'Additional instructions for the AI reviewer'
    required: false
    default: ''
  model:
    description: 'Model to use (provider-specific, e.g., gpt-4-turbo-preview for OpenAI, gemini-pro for Google)'
    required: false
    default: 'gpt-4o-mini'
  pr_title:
    description: 'Title of the pull request'
    required: false
    default: ${{ github.event.pull_request.title }}
  pr_description:
    description: 'Description of the pull request'
    required: false
    default: ${{ github.event.pull_request.body }}
  pr_state:
    description: 'State of the pull request'
    required: false
    default: ${{ github.event.pull_request.state }}
  pr_author:
    description: 'Author of the pull request'
    required: false
    default: ${{ github.event.pull_request.user.login }}
  github_repository:
    description: 'Repository of the pull request'
    required: false
    default: ${{ github.repository }}
  skip_fixes:
    description: 'Skip fix generation'
    required: false
    default: 'false'
  
  skip_generated_pr_review:
    description: 'Skip generated PR review'
    required: false
    default: 'true'
  
  log_level:
    description: 'Logging level'
    required: false
    default: 'INFO'

runs:
  using: 'composite'

  steps:
    
    - name: Skip if has skip-review label
      id: check_if_skip_review_label
      shell: bash
      run: |
        if [[ ${{ contains(github.event.pull_request.labels.*.name, 'skip-review') }} == true ]]; then
          echo "SKIP_REVIEW_LABEL=0" >> $GITHUB_OUTPUT
        else
          echo "SKIP_REVIEW_LABEL=1" >> $GITHUB_OUTPUT
        fi
      continue-on-error: true

    - name: Check if review is requested
      id: check_if_review_requested
      shell: python
      env:
        PR_TITLE: ${{ inputs.pr_title }}
        PR_DESCRIPTION: ${{ inputs.pr_description }}
        PR_STATE: ${{ inputs.pr_state }}
        MERGE_PATTERN: \b(?:merged|closed)\b
        BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        BRANCH_NAME_PATTERN: \b(?:otterai/fixes-for-pr-\d+)\b
        SKIP_REVIEW_LABEL: ${{ steps.check_if_skip_review_label.outputs.SKIP_REVIEW_LABEL }}
        PATTERN: \b((?:no|skip)-(?:review|otter|otterai)|otter-(?:no|bye|restricted))(?:,((?:no|skip)-(?:review|otter|otterai)|otter-(?:no|bye|restricted)))*\b
      run: |
        import os
        import re

        pr_title = os.environ['PR_TITLE']
        pattern = os.environ['PATTERN']
        pr_description = os.environ['PR_DESCRIPTION']
        merge_pattern = os.environ['MERGE_PATTERN']
        pr_state = os.environ['PR_STATE']
        branch_name = os.environ['BRANCH_NAME']
        branch_name_pattern = os.environ['BRANCH_NAME_PATTERN']

        if re.search(pattern, pr_title, re.IGNORECASE) or re.search(merge_pattern, pr_state, re.IGNORECASE) or re.search(pattern, pr_description, re.IGNORECASE) or re.search(branch_name_pattern, branch_name, re.IGNORECASE) or os.environ.get('SKIP_REVIEW_LABEL', '1') == '0':
            print("🦦 No review requested, skipping code review")
            with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                f.write("code_review_requested=false\n")
        else:
            print("🔍 Code review requested")
            with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                f.write("code_review_requested=true\n")
   
    - name: Echo code review requested
      shell: bash
      run: |
        echo "Code review requested: ${{ steps.check_if_review_requested.outputs.code_review_requested }}"

    - name: Add skip comment if review is skipped
      if: steps.check_if_review_requested.outputs.code_review_requested == 'false'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        PR_NUMBER: ${{ inputs.pr_number }}
        COMMENT: "Hey @${{inputs.pr_author}}! 🦦 Looks like you've requested a vacation from code review! I'll be chilling with my fish friends instead! 🐠 Have a splashing good day! 🌊"
      run: |
        # First check if comment already exists
        EXISTING_COMMENTS=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments?since=${{ github.event.pull_request.created_at }}")
        
        if ! echo "$EXISTING_COMMENTS" | grep -q "$COMMENT"; then
          # Comment doesn't exist, so create it
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
            -d "{\"body\":\"$COMMENT\"}"
        else
          echo "Skip comment already exists"
        fi

    - name: Add a label to the PR if review is skipped
      if: steps.check_if_review_requested.outputs.code_review_requested == 'false'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        gh label create "skip-review" --description "Skip review" --color "f0f0f0" -f
        gh pr edit ${{ env.PR_NUMBER }} --add-label "skip-review"
    
    - name: Add a label to the PR if review is requested
      if: steps.check_if_review_requested.outputs.code_review_requested == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        gh label create "cori-ai-review" --description "Cori AI review" --color "9C27B0" -f
        gh pr edit ${{ env.PR_NUMBER }} --add-label "cori-ai-review"
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: "3.12"   

    - name: Review Code with CoriAI ✨
      shell: bash
      if: steps.check_if_review_requested.outputs.code_review_requested == 'true'
      run: |
        echo "🔍 Detective Otter on the case! Time to review some code! 🕵️‍♂️"
        pip install --no-cache-dir cori-ai --upgrade pip
        python -m cori_ai.review
        echo "🎉 Code review complete! 🎉"
        echo "🐟 Fishy code review results! 🐟"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        INPUT_OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        INPUT_GOOGLE_API_KEY: ${{ inputs.google_api_key }}
        INPUT_GROQ_API_KEY: ${{ inputs.groq_api_key }}
        INPUT_OLLAMA_API_KEY: ${{ inputs.ollama_api_key }}
        INPUT_OLLAMA_BASE_URL: ${{ inputs.ollama_base_url }}
        INPUT_MISTRAL_API_KEY: ${{ inputs.mistral_api_key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_EXTRA_PROMPT: ${{ inputs.extra_prompt }}
        PR_TITLE: ${{ inputs.pr_title }}
        PR_DESCRIPTION: ${{ inputs.pr_description }}
        PR_STATE: ${{ inputs.pr_state }}
        PR_AUTHOR: ${{ inputs.pr_author }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        INPUT_SKIP_FIXES: ${{ inputs.skip_fixes }}
        INPUT_SKIP_GENERATED_PR_REVIEW: ${{ inputs.skip_generated_pr_review }}

    - name: Add a label to the PR if review is complete
      if: steps.check_if_review_requested.outputs.code_review_requested == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        gh label create "cori-ai-review-complete" --description "Cori AI review complete" --color "2ECC71" -f
        gh pr edit ${{ env.PR_NUMBER }} --add-label "cori-ai-review-complete"
