name: '🦦 Dr. OtterAI Code Review, PhD'
description: '🤖 AI-powered code reviews for pull requests using GPT models, by a smart otter with a PhD! 🎓'
author: 'fofsinx'

branding:
  icon: 'code'
  color: 'yellow'

inputs:
  openai_api_key:
    description: 'OpenAI API key for code review'
    required: true
  openai_base_url:
    description: 'OpenAI API base URL (optional)'
    required: false
    default: 'https://api.openai.com/v1'
  github_token:
    description: 'GitHub token for PR access'
    required: true
    default: ${{ github.token }}
  extra_prompt:
    description: 'Additional instructions for the AI reviewer'
    required: false
    default: ''
  model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-4-turbo-preview'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run OtterAI Code Review
      shell: bash
      env:
        INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        INPUT_OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_EXTRA_PROMPT: ${{ inputs.extra_prompt }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        python -m otterai.main 