name: 'OtterAI Code Review'
description: 'AI-powered code review and fix generation'
author: 'Harsh Vardhan Goswami'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  pr_number:
    description: 'Pull request number'
    required: true
  
  provider:
    description: 'LLM provider to use (openai, gemini, groq, or mistral, or anthropic, or ollama)'
    required: false
    default: 'openai'
  
  model:
    description: 'Model to use (provider-specific)'
    required: false
  
  openai_api_key:
    description: 'OpenAI API key'
    required: false
  
  openai_base_url:
    description: 'OpenAI API base URL'
    required: false
    default: 'https://api.openai.com/v1'
  
  google_api_key:
    description: 'Google API key'
    required: false
  
  groq_api_key:
    description: 'Groq API key'
    required: false
  
  mistral_api_key:
    description: 'Mistral API key'
    required: false
  
  skip_fixes:
    description: 'Skip fix generation'
    required: false
    default: 'false'
  
  skip_generated_pr_review:
    description: 'Skip generated PR review'
    required: false
    default: 'true'
  
  extra_prompt:
    description: 'Additional instructions for the AI reviewer'
    required: false
    default: ''
  
  log_level:
    description: 'Logging level'
    required: false
    default: 'INFO'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
    
    - name: Install OtterAI
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # Install OtterAI directly from GitHub or PyPI
        pip install otterai
        # Only install requirements if they exist in the action path
        if [ -f "${{ github.action_path }}/requirements.txt" ]; then
          pip install -r ${{ github.action_path }}/requirements.txt
        fi
    
    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        INPUT_OPENAI_BASE_URL: ${{ inputs.openai_base_url }}
        INPUT_GOOGLE_API_KEY: ${{ inputs.google_api_key }}
        INPUT_GROQ_API_KEY: ${{ inputs.groq_api_key }}
        INPUT_MISTRAL_API_KEY: ${{ inputs.mistral_api_key }}
        INPUT_SKIP_FIXES: ${{ inputs.skip_fixes }}
        INPUT_SKIP_GENERATED_PR_REVIEW: ${{ inputs.skip_generated_pr_review }}
        INPUT_EXTRA_PROMPT: ${{ inputs.extra_prompt }}
        INPUT_LOG_LEVEL: ${{ inputs.log_level }}
      run: otterai review