name: Test OtterAI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  bash-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run bash tests
        shell: bash
        run: |
          echo "Running bash tests..."
          chmod +x tests/test_action_checks.sh
          ./tests/test_action_checks.sh

  # Run tests
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s otterai/tests -p 'test_*.py'

  
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get full history for better context

      - name: OtterAI Code Review
        uses: ./  # Uses the action from the current repository
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          openai_base_url: ${{ secrets.OPENAI_BASE_URL }}
          github_token: ${{ secrets.GH_TOKEN }}
          model: 'gpt-4o-mini'
          extra_prompt: |
            Please focus on:
            - Python best practices and PEP8 compliance
            - Security implications of the changes
            - Performance optimizations
            - Code maintainability and documentation
            - Potential edge cases and error handling 
            - Use emojis in your comments and be very specific.